import express from 'express'
import https from 'node:https'
import path from 'node:path'
import fs from 'node:fs/promises'
import { EventEmitter } from 'node:events'

const app = express()
const port = process.env.PORT || 3000
const ev = new EventEmitter()
const dataDir = path.join(import.meta.dirname, 'data')
const isProd = process.env.NODE_ENV === 'production'

// SSE endpoint for upload progress
app.get('/stream', (req, res) => {
  res.setHeader('Content-Type', 'text/event-stream')
  res.setHeader('Cache-Control', 'no-cache')
  res.setHeader('Connection', 'keep-alive')
  res.write(':\n\n')

  const timer = setInterval(() => {
    res.write(':\n\n')
  }, 50000)

  const onData = (data) => {
    res.write(`data: ${data}\n\n`)
  }
  ev.on('data', onData)

  req.on('close', () => {
    clearInterval(timer)
    ev.removeListener('data', onData)
  })
})

// File download (delete after successful download)
app.get('/d/:fileId', (req, res) => {
  const id = req.params.fileId
  const filepath = path.join(dataDir, id)
  res.download(filepath, async (err) => {
    if (err) {
      if (!res.headersSent) {
        res.status(404).send('File not found')
      }
      return
    }
    try {
      await fs.unlink(filepath)
    } catch (unlinkErr) {
      console.error('Unlink error:', unlinkErr)
    }
  })
})

// File upload chunk via URL parameter
app.get('/u/:fileId/:content', async (req, res) => {
  try {
    const id = req.params.fileId
    const raw = Buffer.from(req.params.content, 'base64')
    const filepath = path.join(dataDir, id)

    await fs.appendFile(filepath, raw)
    const stats = await fs.stat(filepath)
    ev.emit('data', JSON.stringify({ id, type: 'progress', len: stats.size }))
    res.send('OK')
  } catch (err) {
    console.error('Upload error:', err)
    res.status(500).send('Error')
  }
})

// Scanner ready notification
app.get('/ready/:fileId', (req, res) => {
  const id = req.params.fileId
  ev.emit('data', JSON.stringify({ id, type: 'ready' }))
  res.send('OK')
})

// Transfer complete notification
app.get('/complete/:fileId', (req, res) => {
  const id = req.params.fileId
  ev.emit('data', JSON.stringify({ id, type: 'complete' }))
  res.send('OK')
})

if (isProd) {
  // Production: serve pre-built static files
  app.use(express.static(path.join(import.meta.dirname, 'dist')))
  app.get('*', (req, res) => {
    res.sendFile(path.join(import.meta.dirname, 'dist', 'index.html'))
  })

  app.listen(port, '0.0.0.0', () => {
    console.log(`Shawshank server listening on port ${port}`)
  })
} else {
  // Development: embed Vite dev server as middleware with HTTPS
  const { createServer: createViteServer } = await import('vite')
  const vite = await createViteServer({
    server: { middlewareMode: true },
    appType: 'spa',
  })
  app.use(vite.middlewares)

  // Use the certificate generated by @vitejs/plugin-basic-ssl
  const { getCertificate } = await import('@vitejs/plugin-basic-ssl')
  const cert = await getCertificate('node_modules/.vite/basic-ssl')
  https.createServer({ key: cert, cert }, app).listen(port, '0.0.0.0', () => {
    console.log(`Shawshank dev server listening on https://localhost:${port}`)
  })
}

// Periodic cleanup of old files (30 minutes)
setInterval(async () => {
  try {
    const files = await fs.readdir(dataDir)
    const now = Date.now()
    for (const file of files) {
      if (file === '.gitkeep') continue
      const target = path.join(dataDir, file)
      const stats = await fs.stat(target)
      if (now - stats.mtimeMs > 30 * 60 * 1000) {
        await fs.unlink(target)
        console.log(`${target} was deleted.`)
      }
    }
  } catch (err) {
    console.error('Cleanup error:', err)
  }
}, 10000)
